function flag = chkConsistency(this)
% chkConsistency  Check consistence of model.component.Equation properties.
%
% Backend IRIS function.
% No help provided.

% -IRIS Macroeconomic Modeling Toolbox.
% -Copyright (c) 2007-2019 IRIS Solutions Team.

%--------------------------------------------------------------------------

nEqtn = length(this.Input);

flag = length(this.Type)==nEqtn ...
    && isnumeric(this.Type) ...
    && length(this.Label)==nEqtn ...
    && iscellstr(this.Label) ...
    && length(this.Alias)==nEqtn ...
    && iscellstr(this.Alias) ...
    && length(this.Dynamic)==nEqtn ...
    && iscell(this.Dynamic) ...
    && length(this.Steady)==nEqtn ...
    && iscell(this.Steady) ...
    && length(this.IxHash)==nEqtn ...
    && islogical(this.IxHash);

if ~flag
    return
end

% Check index of nonlinear equations.
ixHash = cellfun(@(x) ~isempty(strfind(x, '=#')), this.Input);
flag = isequal(this.IxHash, ixHash);

end
