function flag = testCompatible(this, obj)
flag = isa(this, 'model.Incidence') && isa(obj, 'model.Incidence') ...
    && isequal(this.Shift, obj.Shift) ...
    && isequal(this.Matrix, obj.Matrix);
end
