classdef condformatobj < handle
% condformatobj  [Not a public class] Conditional format object.
%
% Backend IRIS class.
% No help provided.

% -IRIS Macroeconomic Modeling Toolbox.
% -Copyright (c) 2007-2022 IRIS Solutions Team.
    
    properties
        test = { };
        format = { };
    end
    
    properties (Constant)
        attribute = { ...
            'value', ...
            'text', ...
            'mark', ...
            'date', ...
            'year', ...
            'period', ...
            'freq', ...
            'rowname', ...
            'colname', ...
            'row', ...
            'col', ...
            'rowvalues', ...
            'colvalues', ...
            'allvalues', ...
            'highlight', ...
            };
    end
    
    methods
        
        function This = condformatobj(varargin)
        end
        
        varargout = assign(varargin)        
        varargout = testnformat(varargin)        
        
    end
    
end
