function flag = testCompatible(this, obj)
flag = isa(this, 'model.component.Equation') && isa(obj, 'model.component.Equation') ...
    && length(this.Input)==length(obj.Input) ...
    && all(this.Type==obj.Type);
end
