function flag = checkConsistency(this)

flag = checkConsistency@iris.mixin.GetterSetter(this) && ...
       checkConsistency@iris.mixin.UserDataContainer(this) && ...
       checkConsistency(this.Quantity) && ...
       checkConsistency(this.Equation) && ...
       model.component.Pairing.checkConsistency(this.Pairing, this.Quantity, this.Equation);

end%

