function Def = dest( )
% dest  [Not a public function] Default options for dest package functions.
%
% Backend IRIS function.
% No help provided.

% -IRIS Macroeconomic Modeling Toolbox.
% -Copyright (c) 2007-2020 IRIS Solutions Team.

%--------------------------------------------------------------------------

Def = struct( );

Def.kcluster = { ...
    'k,maxk', 4, @(x) isintscalar(x) && x>0, ...
    'selectk,select', 'bic', @(x) any(strcmpi(x,{'bic','fixed'})), ...
    'maxit', 500, @(x) isintscalar(x) && x>0, ...
    'tol', 1e-6, @(x) isnumericscalar(x), ...
    'vectorized', true, @islogical, ...
    'display', false, @islogical, ...
    };

end