function Def = SVAR( )
% SVAR  Default options for SVAR class functions.
%
% Backend IRIS function.
% No help provided.

% -IRIS Macroeconomic Modeling Toolbox.
% -Copyright (c) 2007-2020 IRIS Solutions Team.

%--------------------------------------------------------------------------

Def = struct( );

outputFmt = { ...
    'output','auto',@(x) isanystri(x,{'auto','dbase','tseries','array'}), ...
    };

Def.sort = [...
    outputFmt, { ...
    'progress',false,@islogicalscalar, ...
    }];

Def.SVAR = [ ...
    outputFmt, { ...
    'MaxIter',0,@(x) isnumericscalar(x) && x >= 0, ...
    'method','chol',@(x) isanystri(x,{'chol','qr','svd','householder'}), ...
    'ndraw',0,@(x) isnumericscalar(x) && x >= 0, ...
    'reorder,ordering',[ ],@(x) isempty(x) || isnumeric(x) || iscellstr(x), ...
    'progress',false,@islogicalscalar, ...
    'backorderresiduals,backorderresidual,reorderresiduals,reorderresidual', ...
    true,@islogical, ...
    'rank',Inf,@isnumericscalar, ...
    'std',1,@isnumericscalar, ...
    'test','',@ischar, ...
    }];


Def.fevd = { 
    'MatrixFormat', 'namedmat', @namedmat.validateMatrixFormat
}; %#ok<CCAT1>

end
