function flag = isequal(this, that)

flag = isa(this, 'tseries') && isa(that, 'tseries') ...
    && isequaln(this.Comment, that.Comment) ...
    && isequaln(this.UserData, that.UserData) ...
    && isequaln(this.Caption, that.Caption) ...
    && isequaln(this.BaseYear, that.BaseYear) ...
    && isequaln(this.Start, that.Start) ...
    && isequaln(this.Data, that.Data);

end%

