function flag = chkConsistency(this)
% chkConsistency  Check consistency of model.component.Equation properties.
%
% Backend IRIS function.
% No help provided.

% -IRIS Macroeconomic Modeling Toolbox.
% -Copyright (c) 2007-2018 IRIS Solutions Team.

%--------------------------------------------------------------------------

nQuan = length(this.Name);

flag = length(this.Type)==nQuan ...
    && isnumeric(this.Type) ...
    && length(this.Label)==nQuan ...
    && iscellstr(this.Label) ...
    && length(this.Alias)==nQuan ...
    && iscellstr(this.Alias) ...
    && length(this.IxLog)==nQuan ...
    && islogical(this.IxLog) ...
    && length(this.IxLagrange)==nQuan ...
    && islogical(this.IxLagrange) ...    
    && length(this.IxObserved)==nQuan ...
    && islogical(this.IxObserved) ...
    && size(this.Bounds,1)==4 ...
    && size(this.Bounds,2)==nQuan ...
    && isnumeric(this.Bounds);

if ~flag
    return
end

flag = numel(this.Name)==numel(unique(this.Name)) ...
    && ~any( strncmp(this.Name, 'std_', 4) ) ...
    && ~any( strncmp(this.Name, 'corr_', 5) ) ...
    && ~any( strcmp(this.Name, model.RESERVED_NAME_TTREND) ) ...
    && ~any( strcmp(this.Name, model.RESERVED_NAME_LINEAR) );

end
