function varargout = beta(varargin)
utils.warning('obsolete', ...
    ['The package name logprior is obsolete and will be removed from future versions of IRIS. ', ...
    'Use logdist.beta instead.']);
[varargout{1:nargout}] = logdist.beta(varargin{:});
end