function varargout = gamma(varargin)
utils.warning('obsolete', ...
    ['The package name logprior is obsolete and will be removed from future versions of IRIS. ', ...
    'Use logdist.gamma instead.']);
[varargout{1:nargout}] = logdist.gamma(varargin{:});
end