function varargout = lognormal(varargin)
utils.warning('obsolete', ...
    ['The package name logprior is obsolete and will be removed from future versions of IRIS. ', ...
    'Use logdist.lognormal instead.']);
[varargout{1:nargout}] = logdist.lognormal(varargin{:});
end