function varargout = uniform(varargin)
utils.warning('obsolete', ...
    ['The package name logprior is obsolete and will be removed from future versions of IRIS. ', ...
    'Use logdist.uniform instead.']);
[varargout{1:nargout}] = logdist.uniform(varargin{:});
end