name: Broadcast push to bleeding


on:
  push:
    branches: [ "bleeding" ]
  workflow_dispatch:


jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Run dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: IRIS-Solutions-Team/iris-reference
          token: ${{ secrets.IRIS_REFERENCE_TOKEN }}
          event-type: iris-toolbox-push-bleeding
          client-payload: '{"ref": "${{ github.ref }}"}'

