# This is a basic workflow to help you get started with Actions

name: Update rephrase plugin

on:
  repository_dispatch:
    types: [rephrase-release-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone rephrase dist
      uses: actions/checkout@v2
      with:
        repository: OGResearch/rephrase
        ref: refs/heads/dist
        path: rephrase
        token: ${{ secrets.PAT_ALL_SCOPES }}
        
    - name: Get short hash of latest rephrase commit
      id: rephrase_commit
      run: |
        cd $GITHUB_WORKSPACE/rephrase
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"      
                
    - name: Clone iris-toolbox master
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        path: iris
        
    - name: Update subtree, push new commit
      run: |
        cd $GITHUB_WORKSPACE/iris
        git subtree pull -P Plugins/.rephrase ../rephrase dist
        git add .
        rephrase_commit=$
        git commit -m "Update rephrase subtree from dist ${{ steps.rephrase_commit.outputs.sha_short }}"
        git push
        
