name: Package IrisT Release

on:
  push:
    tags:
      - 'Ready-*'
  
  workflow_dispatch:
  
  
jobs:
  build:
    name: Package IrisT Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Gather release notes
        run: |
          latest_release=$(git log | grep -oP "Release-[^ ]+" -m 1)
          log=$(git log "$latest_release"..HEAD)
          echo "" > .release-notes
          echo "### Bug fixes:" >> .release-notes
          echo "$log" | grep "##" | sed "s/^ *#\{2,5\} \?//" >> .release-notes
          echo ""  >> .release-notes
          echo "### New features:" >> .release-notes
          echo "$log"| grep ">>" | sed "s/^ *>\{2,5\} \?//" >> .release-notes
          
      - name: Name the release
        id: name
        run: |
          release="${{ github.ref }}"
          if test "_$release" == "_refs/heads/master"; then
            release="Release-Unknown"
          else
            release="Release-${release#'Ready-'}"
          fi
          echo "::set-output name=release::$release"
          
      - name: Echo release name
        run: |
          echo "${{steps.name.outputs.release}}"
          
      - name: Publish release
        if: ${{ success() }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: .release-notes
          draft: true
          prerelease: false
          
