name: Package IrisT Release

on:
  workflow_dispatch:
  
  
jobs:
  build:
    name: Package IrisT Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Gather release notes
        run: |
          latest_release=$(git log | ggrep -oP "Release-[^ ]+" -m 1)

          log=$(git log "$latest_release"..HEAD)

          echo "### Bug fixes:" 
          echo "$log" | ggrep "##" | gsed "s/^ *#\{2,5\} \?//" 

          echo "" 

          echo "### New features:" 
          echo "$log"| ggrep ">>" | gsed "s/^ *>\{2,5\} \?//" 
