name: Package IrisT Release

on:
  workflow_dispatch:
  
  
jobs:
  build:
    name: Package IrisT Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Gather release notes
        run: |
          latest_release=$(git log | grep -oP "Release-[^ ]+" -m 1)
          log=$(git log "$latest_release"..HEAD)
          echo "" > .release-notes
          echo "### Bug fixes:" >> .release-notes
          echo "$log" | grep "##" | sed "s/^ *#\{2,5\} \?//" >> .release-notes
          echo ""  >> .release-notes
          echo "### New features:" >> .release-notes
          echo "$log"| grep ">>" | sed "s/^ *>\{2,5\} \?//" >> .release-notes
          
      - name: Echo release notes
        run: |
          cat .release-notes
          
