name: Update pre-r2019b branch

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Update the pre-r2019b branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
          path: iris-toolbox      

      - name: Test
        run: |
          cd $GITHUB_WORKSPACE/iris-toolbox
          git status
          git branch
          
