name: Update pre-r2019b branch

on:
  push:
    tags: [ 'pre-r2019b*' ]

  workflow_dispatch:

jobs:
  build:
    name: Update the pre-r2019b branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          fetch-depth: 100
          ref: master
          path: iris-toolbox      

      - name: Test
        run: |
          cd $GITHUB_WORKSPACE/iris-toolbox
          git status
          git branch
          git switch pre-r2019b
          cat +iris/startup.m
          
